version: '3.8'
services:
    db:
        image: mysql:8.0
        container_name: mysql_db
        environment:
            MYSQL_DATABASE: news_api
            MYSQL_USER: admin
            MYSQL_ROOT: root
            MYSQL_PASSWORD: admin
            MYSQL_ROOT_PASSWORD: root
        volumes:
            - ./storage/dbdata:/var/lib/mysql
        ports:
            - 8889:3306
    main:
        build:
            context: .
            dockerfile: Dockerfile
        depends_on:
            - db
        command: 'php artisan migrate'
        command: 'php artisan serve --host=0.0.0.0'
        volumes:
            - .:/app
        ports:
            - 8000:8000
